version: '1'

services:
  server:
    pull_policy: build
    build: 
      context: .
      dockerfile: Backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - VIRTUAL_HOST=academy.loomel.tech
      - LETSENCRYPT_HOST=academy.loomel.tech
      - VIRTUAL_PORT=8080
