version: '3'

services:
  # server:
  #   pull_policy: build
  #   build: 
  #     context: .
  #     dockerfile: Backend/Dockerfile
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - VIRTUAL_HOST=academy.loomel.tech
  #     - LETSENCRYPT_HOST=academy.loomel.tech
  #     - VIRTUAL_PORT=8080
  #   networks:
  #     - proxy
  frontend:
    pull_policy: build
    build: 
      context: Frontend
      dockerfile: Dockerfile
    environment:
      - VIRTUAL_HOST=academy.loomel.tech
      - LETSENCRYPT_HOST=academy.loomel.tech
    networks:
      - proxy
networks:
  proxy:
    external: true